In [1]:
import numpy as np

# Found that implementation of dsign did not work well

In [17]:
# After first QR step
A = np.array([-0.2108698262446318, -0.075653990821633585, 0.021032386738913472, 0.021243036364792137, 0, 0.46177600745567071, -0.27675087180598412, 0.15084932466895898, -0.14047331582313977, 0.016275718712806378, -0.41712001759860007, 0.10734967917325294, 0.27409348686634638, -0.025138417928122107, -0.00040611921966940412, -0.16537422543417507, 0.062716131610413839, 0.16977010716127769, 0.32639369400872814, 0.033779674668232104, -0.14797395304750091, -0.04030200658115364, 0.020384063404238907, 0.53867781610965959, -0.15912154960401922])

B=np.array([-0.2108698262446318, -0.075653990821633585, 0.021032386738913472, 
  0.021243036364792137, 0, 0.46177600745567071, -0.27675087180598412, 
  0.15084932466895898, -0.14047331582313977, 0.016275718712806378, 
  -0.41712001759860007, 0.10734967917325294, 0.27409348686634638, 
  -0.025138417928122107, -0.00040611921966940412, -0.16537422543417507, 
  0.062716131610413839, 0.16977010716127769, 0.32639369400872814, 
  0.033779674668232104, -0.14797395304750091, -0.04030200658115364, 
  0.020384063404238907, 0.53867781610965959, -0.15912154960401922])
D=np.array([-0.2108698262446318, -0.075653990821633585, 0.021032386738913472, 
  0.021243036364792137, 0, 0.46177600745567071, -0.27675087180598412, 
  0.15084932466895898, -0.14047331582313977, 0.016275718712806378, 
  -0.41712001759860007, 0.10734967917325294, 0.27409348686634638, 
  -0.025138417928122107, -0.00040611921966940412, -0.16537422543417507, 
  0.062716131610413839, 0.16977010716127769, 0.32639369400872814, 
  0.033779674668232104, -0.14797395304750091, -0.04030200658115364, 
  0.020384063404238907, 0.53867781610965959, -0.15912154960401922])
print(B-D)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [3]:
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [4]:
print(0.48762069805061592 - 0.48762069805061592)

0.0


In [5]:
# After second QR step
A=np.array([-0.47421221674714276, -0.41310496904703403, -0.070062418234365931, 0.0050506211773938738, 0, 0.19718496616390291, -0.05874403400692943, 0.01609797931156846, -0.0058355358908477638, -0.00041299028825146817, -0.15031747484134081, -0.29309587230135692, 0.3807362947833639, -0.027180100897181238, 0.0017040073887292732, -0.046690823422245141, -0.026736852328922173, 0.18035582688410123, 0.29940139430402851, -0.00023459877821010826, 0.020217779269935995, 0.13576651023909425, -0.1905226962725842, -0.47043195777913077, -0.19343650511288057])
B=np.array([-0.47421221674714276, -0.41310496904703403, -0.070062418234365931, 
  0.0050506211773938738, 0, 0.19718496616390291, -0.05874403400692943, 
  0.01609797931156846, -0.0058355358908477638, -0.00041299028825146817, 
  -0.15031747484134081, -0.29309587230135692, 0.3807362947833639, 
  -0.027180100897181238, 0.0017040073887292732, -0.046690823422245141, 
  -0.026736852328922173, 0.18035582688410123, 0.29940139430402851, 
  -0.00023459877821010826, 0.020217779269935995, 0.13576651023909425, 
  -0.1905226962725842, -0.47043195777913077, -0.19343650511288057])
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [6]:
# After third QR step
A = np.array([-0.22596270884144765, -0.073372531625459911, -0.0017254205636837178, -0.0006089392619263933, 0, 0.54033821972986773, -0.29992438457212989, 0.012212741021047748, 0.0047056146952490843, -1.9470011963240818e-06, -0.29436987855064994, -0.016364409980911224, 0.30829454290654545, -0.023688010280335233, -1.1178696535063609e-05, -0.17142159410534685, 0.01759580770722774, 0.18330992302374061, 0.3649978944005593, 2.4660479348403552e-10, -0.13420233673390902, -0.049831801177850778, -0.0084840576253778169, 0.50559080114117161, -0.19366041067308751])
B = np.array([-0.22596270884144765, -0.073372531625459911, -0.0017254205636837178, 
  -0.0006089392619263933, 0, 0.54033821972986773, -0.29992438457212989, 
  0.012212741021047748, 0.0047056146952490843, -1.9470011963240818e-06, 
  -0.29436987855064994, -0.016364409980911224, 0.30829454290654545, 
  -0.023688010280335233, -1.1178696535063609e-05, -0.17142159410534685, 
  0.01759580770722774, 0.18330992302374061, 0.3649978944005593, 
  2.4660479348403552e-10, -0.13420233673390902, -0.049831801177850778, 
  -0.0084840576253778169, 0.50559080114117161, -0.19366041067308751])
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [7]:
# After fourth QR step
A=np.array([-0.45271806292609218, -0.45431137343676126, -0.0060268950725445632, 0.00038495309173527546, 0, 0.16405331735783196, -0.074200335858028849, 0.0012450818539307023, -0.00042619051393000609, -2.0895641896500469e-13, -0.1033782880953331, -0.30853140630179754, 0.36746323028077238, -0.024304761792566881, 1.0476786919510983e-11, -0.044705882811804452, -0.049954347269766872, 0.18338924007997948, 0.30686051261650005, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.45271806292609218, -0.45431137343676126, -0.0060268950725445632, 
  0.00038495309173527546, 0, 0.16405331735783196, -0.074200335858028849, 
  0.0012450818539307023, -0.00042619051393000609, -2.0895641896500469e-13, 
  -0.1033782880953331, -0.30853140630179754, 0.36746323028077238, 
  -0.024304761792566881, 1.0476786919510983e-11, -0.044705882811804452, 
  -0.049954347269766872, 0.18338924007997948, 0.30686051261650005, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [8]:
# First eigenvalue found
a=-0.19366041089271133
b=-0.19366041089271133
print(a-b)

0.0


In [15]:
# After fifth QR step
A=np.array([-0.41083832291502642, -0.12172986031705209, -0.0003443199634602822, -1.7696473858378058e-05, 0, 0.4972714029851279, -0.11549630794875895, -2.3951565579249396e-07, -8.4865194276826012e-08, -2.0895641896500469e-13, -0.24710126067011623, -0.13699663587511932, 0.30666195852575984, 0.024401211304088052, 1.0476786919510983e-11, 0.16524372713743285, 0.056906295052280481, -0.183254416318408, 0.36707801645117699, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.41083832291502642, -0.12172986031705209, -0.0003443199634602822, 
  -1.7696473858378058e-05, 0, 0.4972714029851279, -0.11549630794875895, 
  -2.3951565579249396e-07, -8.4865194276826012e-08, -2.0895641896500469e-13, 
  -0.24710126067011623, -0.13699663587511932, 0.30666195852575984, 
  0.024401211304088052, 1.0476786919510983e-11, 0.16524372713743285, 
  0.056906295052280481, -0.183254416318408, 0.36707801645117699, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
C=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(A-B)
print(A-C)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[-2.35849169e-01 -3.42409241e-02 -3.44319963e-04 -1.76964739e-05
  0.00000000e+00 -3.42407946e-02  2.35849214e-01 -2.39515656e-07
 -8.48651943e-08  0.00000000e+00 -3.04778207e-01 -1.07774145e-01
  1.11686302e-03 -1.58419392e-01  0.00000000e+00 -1.60221780e-01
  7.31123483e-02 -1.58419379e-01 -1.11690797e-03  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]


In [14]:
# After sixth QR Step
A=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 0.014730937871014128, 0.18282060310512152, 0.30554509550893832, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, 
  -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 
  2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, 
  -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, 
  -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 
  0.014730937871014128, 0.18282060310512152, 0.30554509550893832, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
C=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(A-B)
print(A-C)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[-1.12062288e-01  1.56732570e-02  3.43796639e-08 -1.36054215e-09
  0.00000000e+00  1.56732570e-02  1.12062288e-01  2.35208786e-15
  8.51608309e-16  0.00000000e+00 -3.77720840e-01 -3.21154140e-02
  6.26498289e-02 -2.07655640e-01  0.00000000e+00 -3.88422505e-01
  3.09369911e-02  2.07655640e-01 -6.26498289e-02  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]


In [20]:
# After 7th QR Step
A=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 0.014730937871014128, 0.18282060310512152, 0.30554509550893832, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, 
  -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 
  2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, 
  -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, 
  -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 
  0.014730937871014128, 0.18282060310512152, 0.30554509550893832, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
D=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, 
  -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 
  2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, 
  -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, 
  -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 
  0.014730937871014128, 0.18282060310512152, 0.30554509550893832, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(D-B)
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [19]:
# After 8th run
A=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, 
  -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, 
  1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 
  -0.057676946334842438, 0.029222490499241156, 0.30554509550893832, 
  0.18282060310512155, 1.0476786919510983e-11, -0.32546550711829891, 
  0.016206053208934101, -0.024835037056909537, 0.36819492441980595, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
C=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
D=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, 
  -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, 
  1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 
  -0.057676946334842438, 0.029222490499241156, 0.30554509550893832, 
  0.18282060310512155, 1.0476786919510983e-11, -0.32546550711829891, 
  0.016206053208934101, -0.024835037056909537, 0.36819492441980595, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(D-B)
print(A-C)
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.69778549e-32
  0.00000000e+00  0.00000000e+00  1.15353893e-01 -5.84449810e-02
  0.00000000e+00  5.55111512e-17  0.00000000e+00  6.50931014e-01
 -3.24121064e-02  0.00000000e+00  5.55111512e-17  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]


In [21]:
a=0.30554509550893832
b=0.30554509550893832
print(a-b)

0.0


In [22]:
a=0.36819492441980611
b=0.36819492441980611
print(a-b)

0.0


In [23]:
a=-0.0045403564528822488
b=-0.0045403564528822488
print(a-b)

0.0


In [24]:
cFunc=np.array([-0.23928323394900258, -0.024835037056909565, 142644189305586.03, 142644189305585.47, -0.54482832945794091, -0.024835037056909565])
fFunc=np.array([-0.23928323394900258, -0.024835037056909565, 142644189305586.03, 142644189305585.47, -0.54482832945794091, -0.024835037056909565])
print(cFunc - fFunc)

[0. 0. 0. 0. 0. 0.]


In [25]:
cVals=np.array([-0.28705144186659048, -0.80400426453068441, -0.19599573546931517, 3.8414208098663286e-16, 6.1229633025980794, 1])
fVals=np.array([-0.28705144186659048, -0.80400426453068441, -0.19599573546931517, 3.8414208098663286e-16, 6.1229633025980794, 1])
print(cVals - fVals)

[0. 0. 0. 0. 0. 0.]


In [26]:
cVals=np.array([-1.6315531668353667, 1.9715489468858853, 0.23683885619747289, -4.6419260531530689e-16, 0.12012831665760378, -2.354456408746593e-16])
fVals=np.array([-1.6315531668353667, 1.9715489468858853, 0.23683885619747289, -4.6419260531530689e-16, 0.12012831665760378, -2.354456408746593e-16])
print(cVals-fVals)

[0. 0. 0. 0. 0. 0.]


In [28]:
a=-0.29567853852400477
b=-0.29567853852400477
print(a-b)

0.0


In [29]:
a=-0.28705144186659048
b=-0.28705144186659048
print(a-b)

0.0


In [30]:
a=0.29589326937716875
b=0.29589326937716875
print(a-b)

0.0


In [31]:
cVals=np.array([-0.0017875123795834946, -1.3725179113328013e-16])
fVals=np.array([-0.0017875123795834946, -1.3725179113328013e-16])
print(cVals-fVals)

[0. 0.]


In [32]:
cVals=np.array([-0.47494588465432108, -0.3620701511269781, 2.5927442330747491e-15])
fVals=np.array([-0.47494588465432108, -0.3620701511269781, 2.5927442330747491e-15])
print(cVals-fVals)

[0. 0. 0.]


In [33]:
cVals=np.array([0.32546550711830069, 0.016206053208936672, 0.36819492441980595])
fVals=np.array([0.32546550711830069, 0.016206053208936672, 0.36819492441980595])
print(cVals-fVals)

[0. 0. 0.]


In [34]:
cVals=np.array([0.057676946334842508, 0.029222490499241888, 0.18282060310512149])
fVals=np.array([0.057676946334842508, 0.029222490499241888, 0.18282060310512149])
print(cVals-fVals)

[0. 0. 0.]


In [35]:
cVals=np.array([-0.17498915417678346, -0.53151219753951018, 0.3254655071183008])
fVals=np.array([-0.17498915417678346, -0.53151219753951018, 0.3254655071183008])
print(cVals - fVals)

[0. 0. 0.]


In [36]:
cVals=np.array([0.087488936226089484, -0.35134552163880955, 0.016206053208936651])
fVals=np.array([0.087488936226089484, -0.35134552163880955, 0.016206053208936651])
print(cVals-fVals)

[0. 0. 0.]


In [37]:
cVals=np.array([-3.0980238420997561e-16, 2.5720160207901746e-15, 0.36819492441980595])
fVals=np.array([-3.0980238420997561e-16, 2.5720160207901746e-15, 0.36819492441980595])
print(cVals - fVals)

[0. 0. 0.]


In [38]:
fVals=np.array([-1.1528240554549042e-17, -1.3848681318418971e-18, -0.024835037056909565])
cVals=np.array([-1.1528240554549042e-17, -1.3848681318418971e-18, -0.024835037056909565])
print(fVals-cVals)

[0. 0. 0.]


In [39]:
a=-0.087488936226089484
b=-0.087488936226089484
print(a-b)

0.0


In [40]:
cVals=np.array([0.35134552163880955, 1.3278852200233681e-15, -4.7680958425460897e-17])
fVals=np.array([0.35134552163880955, 1.3278852200233681e-15, -4.7680958425460897e-17])
print(cVals-fVals)

[0. 0. 0.]


In [41]:
cVals=np.array([-0.016206053208935346, 0.368194924419806, -0.024835037056909561])
fVals=np.array([-0.016206053208935346, 0.368194924419806, -0.024835037056909561])
print(cVals-fVals)

[0. 0. 0.]


In [42]:
fVals=np.array([-0.029222490499241201, 0.1828206031051216, 0.30554509550893832])
cVals=np.array([-0.029222490499241201, 0.1828206031051216, 0.30554509550893832])
print(cVals-fVals)

[0. 0. 0.]


In [43]:
cVals=np.array([0.53151219753951129, 0.32546550711829891, 0.057676946334842438])
fVals=np.array([0.53151219753951129, 0.32546550711829891, 0.057676946334842438])
print(cVals-fVals)

[0. 0. 0.]


In [45]:
cVals=np.array([-0.35134552163880967, -0.016206053208934101, -0.029222490499241156])
fVals=np.array([-0.35134552163880967, -0.016206053208934101, -0.029222490499241156])
print(cVals-fVals)

[0. 0. 0.]


In [46]:
cVals=np.array([0, 0.368194924419806, 0.1828206031051216])
fVals=np.array([0, 0.368194924419806, 0.1828206031051216])
print(cVals-fVals)

[0. 0. 0.]


In [47]:
cVals=np.array([-1.8488927466117464e-32, -0.024835037056909561, 0.30554509550893832])
fVals=np.array([-1.8488927466117464e-32, -0.024835037056909561, 0.30554509550893832])
print(cVals-fVals)

[0. 0. 0.]


In [48]:
# Sign changes here.

# This comes from a misunderstanding of how dsign works in fortran
# The line that causes the difference is 
# s = dsign(dsqrt(p*p+q*q+r*r),p)

# In this particular instance, p was 0, and the fortran code assigns s to be positive
# However, I assigned it to be negative in this case.

# Note: If changes this breaks things, consider that some hardware has +-0 and *hopefully* this 
# is not the case. If it is, we will need to implement our own hack for it.
a=1.8488927466117464e-32
b=-1.8488927466117464e-32
print(a+b)

0.0


# Now checking for larger issues. Check with file I/O

In [4]:
cFile = open("outputFileC.txt", 'r')
fFile = open("outputFileFortran.txt", 'r')
cArr=[[]]
fArr=[[]]
cStr = cFile.readline()
fStr = fFile.readline()
while (cStr and fStr):
    print(cStr,fStr)
    cStr = cFile.readline()
    fStr = fFile.readline()
    

0.35267634542094949968,0.14581566375876359176,-0.14385956804397848074,-0.51460143626259979843,-0.18837536597057352727,0.00000000000000000000
   0.35267634542094950       0.23560459947820037      -0.11236147496094812       0.16135042651929049        0.0000000000000000        0.0000000000000000       0.14581566375876359       -5.8549535062063562E-002 -0.40637167305857536       0.25505823646367864       0.31518816781709652        0.0000000000000000      -0.14385956804397848      -0.37318330367472591      -0.21318848028601395      -0.59230168745454215       0.33266823517464494       0.10912677193523022      -0.51460143626259980       0.14805001747220325        3.0113389208530017E-002  0.24599518206304410       0.16798665672474944       -4.5259315474781348E-002 -0.18837536597057353        6.8958451930132725E-002 -0.44548197219479280       0.16863246077673644      -0.10347635504439717        2.4425817354872162E-002 -0.16507726039834972       0.73165487340781332      -0.39397214229289623     