In [1]:
import numpy as np

# Found that implementation of dsign did not work well

In [2]:
# After first QR step
A = np.array([-0.2108698262446318, -0.075653990821633585, 0.021032386738913472, 0.021243036364792137, 0, 0.46177600745567071, -0.27675087180598412, 0.15084932466895898, -0.14047331582313977, 0.016275718712806378, -0.41712001759860007, 0.10734967917325294, 0.27409348686634638, -0.025138417928122107, -0.00040611921966940412, -0.16537422543417507, 0.062716131610413839, 0.16977010716127769, 0.32639369400872814, 0.033779674668232104, -0.14797395304750091, -0.04030200658115364, 0.020384063404238907, 0.53867781610965959, -0.15912154960401922])

B=np.array([-0.2108698262446318, -0.075653990821633585, 0.021032386738913472, 
  0.021243036364792137, 0, 0.46177600745567071, -0.27675087180598412, 
  0.15084932466895898, -0.14047331582313977, 0.016275718712806378, 
  -0.41712001759860007, 0.10734967917325294, 0.27409348686634638, 
  -0.025138417928122107, -0.00040611921966940412, -0.16537422543417507, 
  0.062716131610413839, 0.16977010716127769, 0.32639369400872814, 
  0.033779674668232104, -0.14797395304750091, -0.04030200658115364, 
  0.020384063404238907, 0.53867781610965959, -0.15912154960401922])
D=np.array([-0.2108698262446318, -0.075653990821633585, 0.021032386738913472, 
  0.021243036364792137, 0, 0.46177600745567071, -0.27675087180598412, 
  0.15084932466895898, -0.14047331582313977, 0.016275718712806378, 
  -0.41712001759860007, 0.10734967917325294, 0.27409348686634638, 
  -0.025138417928122107, -0.00040611921966940412, -0.16537422543417507, 
  0.062716131610413839, 0.16977010716127769, 0.32639369400872814, 
  0.033779674668232104, -0.14797395304750091, -0.04030200658115364, 
  0.020384063404238907, 0.53867781610965959, -0.15912154960401922])
print(B-D)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [3]:
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [4]:
print(0.48762069805061592 - 0.48762069805061592)

0.0


In [5]:
# After second QR step
A=np.array([-0.47421221674714276, -0.41310496904703403, -0.070062418234365931, 0.0050506211773938738, 0, 0.19718496616390291, -0.05874403400692943, 0.01609797931156846, -0.0058355358908477638, -0.00041299028825146817, -0.15031747484134081, -0.29309587230135692, 0.3807362947833639, -0.027180100897181238, 0.0017040073887292732, -0.046690823422245141, -0.026736852328922173, 0.18035582688410123, 0.29940139430402851, -0.00023459877821010826, 0.020217779269935995, 0.13576651023909425, -0.1905226962725842, -0.47043195777913077, -0.19343650511288057])
B=np.array([-0.47421221674714276, -0.41310496904703403, -0.070062418234365931, 
  0.0050506211773938738, 0, 0.19718496616390291, -0.05874403400692943, 
  0.01609797931156846, -0.0058355358908477638, -0.00041299028825146817, 
  -0.15031747484134081, -0.29309587230135692, 0.3807362947833639, 
  -0.027180100897181238, 0.0017040073887292732, -0.046690823422245141, 
  -0.026736852328922173, 0.18035582688410123, 0.29940139430402851, 
  -0.00023459877821010826, 0.020217779269935995, 0.13576651023909425, 
  -0.1905226962725842, -0.47043195777913077, -0.19343650511288057])
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [6]:
# After third QR step
A = np.array([-0.22596270884144765, -0.073372531625459911, -0.0017254205636837178, -0.0006089392619263933, 0, 0.54033821972986773, -0.29992438457212989, 0.012212741021047748, 0.0047056146952490843, -1.9470011963240818e-06, -0.29436987855064994, -0.016364409980911224, 0.30829454290654545, -0.023688010280335233, -1.1178696535063609e-05, -0.17142159410534685, 0.01759580770722774, 0.18330992302374061, 0.3649978944005593, 2.4660479348403552e-10, -0.13420233673390902, -0.049831801177850778, -0.0084840576253778169, 0.50559080114117161, -0.19366041067308751])
B = np.array([-0.22596270884144765, -0.073372531625459911, -0.0017254205636837178, 
  -0.0006089392619263933, 0, 0.54033821972986773, -0.29992438457212989, 
  0.012212741021047748, 0.0047056146952490843, -1.9470011963240818e-06, 
  -0.29436987855064994, -0.016364409980911224, 0.30829454290654545, 
  -0.023688010280335233, -1.1178696535063609e-05, -0.17142159410534685, 
  0.01759580770722774, 0.18330992302374061, 0.3649978944005593, 
  2.4660479348403552e-10, -0.13420233673390902, -0.049831801177850778, 
  -0.0084840576253778169, 0.50559080114117161, -0.19366041067308751])
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [7]:
# After fourth QR step
A=np.array([-0.45271806292609218, -0.45431137343676126, -0.0060268950725445632, 0.00038495309173527546, 0, 0.16405331735783196, -0.074200335858028849, 0.0012450818539307023, -0.00042619051393000609, -2.0895641896500469e-13, -0.1033782880953331, -0.30853140630179754, 0.36746323028077238, -0.024304761792566881, 1.0476786919510983e-11, -0.044705882811804452, -0.049954347269766872, 0.18338924007997948, 0.30686051261650005, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.45271806292609218, -0.45431137343676126, -0.0060268950725445632, 
  0.00038495309173527546, 0, 0.16405331735783196, -0.074200335858028849, 
  0.0012450818539307023, -0.00042619051393000609, -2.0895641896500469e-13, 
  -0.1033782880953331, -0.30853140630179754, 0.36746323028077238, 
  -0.024304761792566881, 1.0476786919510983e-11, -0.044705882811804452, 
  -0.049954347269766872, 0.18338924007997948, 0.30686051261650005, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [8]:
# First eigenvalue found
a=-0.19366041089271133
b=-0.19366041089271133
print(a-b)

0.0


In [9]:
# After fifth QR step
A=np.array([-0.41083832291502642, -0.12172986031705209, -0.0003443199634602822, -1.7696473858378058e-05, 0, 0.4972714029851279, -0.11549630794875895, -2.3951565579249396e-07, -8.4865194276826012e-08, -2.0895641896500469e-13, -0.24710126067011623, -0.13699663587511932, 0.30666195852575984, 0.024401211304088052, 1.0476786919510983e-11, 0.16524372713743285, 0.056906295052280481, -0.183254416318408, 0.36707801645117699, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.41083832291502642, -0.12172986031705209, -0.0003443199634602822, 
  -1.7696473858378058e-05, 0, 0.4972714029851279, -0.11549630794875895, 
  -2.3951565579249396e-07, -8.4865194276826012e-08, -2.0895641896500469e-13, 
  -0.24710126067011623, -0.13699663587511932, 0.30666195852575984, 
  0.024401211304088052, 1.0476786919510983e-11, 0.16524372713743285, 
  0.056906295052280481, -0.183254416318408, 0.36707801645117699, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
C=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(A-B)
print(A-C)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[-2.35849169e-01 -3.42409241e-02 -3.44319963e-04 -1.76964739e-05
  0.00000000e+00 -3.42407946e-02  2.35849214e-01 -2.39515656e-07
 -8.48651943e-08  0.00000000e+00 -3.04778207e-01 -1.07774145e-01
  1.11686302e-03 -1.58419392e-01  0.00000000e+00 -1.60221780e-01
  7.31123483e-02 -1.58419379e-01 -1.11690797e-03  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]


In [10]:
# After sixth QR Step
A=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 0.014730937871014128, 0.18282060310512152, 0.30554509550893832, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, 
  -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 
  2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, 
  -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, 
  -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 
  0.014730937871014128, 0.18282060310512152, 0.30554509550893832, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
C=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(A-B)
print(A-C)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[-1.12062288e-01  1.56732570e-02  3.43796639e-08 -1.36054215e-09
  0.00000000e+00  1.56732570e-02  1.12062288e-01  2.35208786e-15
  8.51608309e-16  0.00000000e+00 -3.77720840e-01 -3.21154140e-02
  6.26498289e-02 -2.07655640e-01  0.00000000e+00 -3.88422505e-01
  3.09369911e-02  2.07655640e-01 -6.26498289e-02  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]


In [11]:
# After 7th QR Step
A=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 0.014730937871014128, 0.18282060310512152, 0.30554509550893832, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, 
  -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 
  2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, 
  -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, 
  -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 
  0.014730937871014128, 0.18282060310512152, 0.30554509550893832, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
D=np.array([-0.28705144186659048, -0.071815679245749206, 3.4379663563343113e-08, 
  -1.3605421583689403e-09, 0, 0.54718545451985046, -0.23928323394900258, 
  2.3520878648648124e-15, 8.5160830904263836e-16, -2.0895641896500469e-13, 
  -0.32004389379394538, -0.061337904509309732, 0.36819492441980611, 
  -0.024835037056909565, 1.0476786919510983e-11, -0.062956997696291844, 
  0.014730937871014128, 0.18282060310512152, 0.30554509550893832, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(D-B)
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]


In [12]:
# After 8th run
A=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
B=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, 
  -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, 
  1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 
  -0.057676946334842438, 0.029222490499241156, 0.30554509550893832, 
  0.18282060310512155, 1.0476786919510983e-11, -0.32546550711829891, 
  0.016206053208934101, -0.024835037056909537, 0.36819492441980595, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
C=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, -1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 0.057676946334842438, -0.029222490499241156, 0.30554509550893832, 0.1828206031051216, 1.0476786919510983e-11, 0.32546550711829891, -0.016206053208934101, -0.024835037056909537, 0.368194924419806, -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
D=np.array([-0.17498915417678346, -0.087488936226089484, -3.0980238420997561e-16, 
  -1.1528240554549042e-17, 0, 0.53151219753951129, -0.35134552163880967, 
  1.8488927466117464e-32, -1.8488927466117464e-32, -2.0895641896500469e-13, 
  -0.057676946334842438, 0.029222490499241156, 0.30554509550893832, 
  0.18282060310512155, 1.0476786919510983e-11, -0.32546550711829891, 
  0.016206053208934101, -0.024835037056909537, 0.36819492441980595, 
  -1.3716063348109953e-20, 0.0039371318346285754, 0.14265694205133597, 
  -0.16488815496063605, -0.47815573299149267, -0.19366041089271133])
print(D-B)
print(A-C)
print(A-B)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -3.69778549e-32
  0.00000000e+00  0.00000000e+00  1.15353893e-01 -5.84449810e-02
  0.00000000e+00  5.55111512e-17  0.00000000e+00  6.50931014e-01
 -3.24121064e-02  0.00000000e+00  5.55111512e-17  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00]


In [13]:
a=0.30554509550893832
b=0.30554509550893832
print(a-b)

0.0


In [14]:
a=0.36819492441980611
b=0.36819492441980611
print(a-b)

0.0


In [15]:
a=-0.0045403564528822488
b=-0.0045403564528822488
print(a-b)

0.0


In [16]:
cFunc=np.array([-0.23928323394900258, -0.024835037056909565, 142644189305586.03, 142644189305585.47, -0.54482832945794091, -0.024835037056909565])
fFunc=np.array([-0.23928323394900258, -0.024835037056909565, 142644189305586.03, 142644189305585.47, -0.54482832945794091, -0.024835037056909565])
print(cFunc - fFunc)

[0. 0. 0. 0. 0. 0.]


In [17]:
cVals=np.array([-0.28705144186659048, -0.80400426453068441, -0.19599573546931517, 3.8414208098663286e-16, 6.1229633025980794, 1])
fVals=np.array([-0.28705144186659048, -0.80400426453068441, -0.19599573546931517, 3.8414208098663286e-16, 6.1229633025980794, 1])
print(cVals - fVals)

[0. 0. 0. 0. 0. 0.]


In [18]:
cVals=np.array([-1.6315531668353667, 1.9715489468858853, 0.23683885619747289, -4.6419260531530689e-16, 0.12012831665760378, -2.354456408746593e-16])
fVals=np.array([-1.6315531668353667, 1.9715489468858853, 0.23683885619747289, -4.6419260531530689e-16, 0.12012831665760378, -2.354456408746593e-16])
print(cVals-fVals)

[0. 0. 0. 0. 0. 0.]


In [19]:
a=-0.29567853852400477
b=-0.29567853852400477
print(a-b)

0.0


In [20]:
a=-0.28705144186659048
b=-0.28705144186659048
print(a-b)

0.0


In [21]:
a=0.29589326937716875
b=0.29589326937716875
print(a-b)

0.0


In [22]:
cVals=np.array([-0.0017875123795834946, -1.3725179113328013e-16])
fVals=np.array([-0.0017875123795834946, -1.3725179113328013e-16])
print(cVals-fVals)

[0. 0.]


In [23]:
cVals=np.array([-0.47494588465432108, -0.3620701511269781, 2.5927442330747491e-15])
fVals=np.array([-0.47494588465432108, -0.3620701511269781, 2.5927442330747491e-15])
print(cVals-fVals)

[0. 0. 0.]


In [24]:
cVals=np.array([0.32546550711830069, 0.016206053208936672, 0.36819492441980595])
fVals=np.array([0.32546550711830069, 0.016206053208936672, 0.36819492441980595])
print(cVals-fVals)

[0. 0. 0.]


In [25]:
cVals=np.array([0.057676946334842508, 0.029222490499241888, 0.18282060310512149])
fVals=np.array([0.057676946334842508, 0.029222490499241888, 0.18282060310512149])
print(cVals-fVals)

[0. 0. 0.]


In [26]:
cVals=np.array([-0.17498915417678346, -0.53151219753951018, 0.3254655071183008])
fVals=np.array([-0.17498915417678346, -0.53151219753951018, 0.3254655071183008])
print(cVals - fVals)

[0. 0. 0.]


In [27]:
cVals=np.array([0.087488936226089484, -0.35134552163880955, 0.016206053208936651])
fVals=np.array([0.087488936226089484, -0.35134552163880955, 0.016206053208936651])
print(cVals-fVals)

[0. 0. 0.]


In [28]:
cVals=np.array([-3.0980238420997561e-16, 2.5720160207901746e-15, 0.36819492441980595])
fVals=np.array([-3.0980238420997561e-16, 2.5720160207901746e-15, 0.36819492441980595])
print(cVals - fVals)

[0. 0. 0.]


In [29]:
fVals=np.array([-1.1528240554549042e-17, -1.3848681318418971e-18, -0.024835037056909565])
cVals=np.array([-1.1528240554549042e-17, -1.3848681318418971e-18, -0.024835037056909565])
print(fVals-cVals)

[0. 0. 0.]


In [30]:
a=-0.087488936226089484
b=-0.087488936226089484
print(a-b)

0.0


In [31]:
cVals=np.array([0.35134552163880955, 1.3278852200233681e-15, -4.7680958425460897e-17])
fVals=np.array([0.35134552163880955, 1.3278852200233681e-15, -4.7680958425460897e-17])
print(cVals-fVals)

[0. 0. 0.]


In [32]:
cVals=np.array([-0.016206053208935346, 0.368194924419806, -0.024835037056909561])
fVals=np.array([-0.016206053208935346, 0.368194924419806, -0.024835037056909561])
print(cVals-fVals)

[0. 0. 0.]


In [33]:
fVals=np.array([-0.029222490499241201, 0.1828206031051216, 0.30554509550893832])
cVals=np.array([-0.029222490499241201, 0.1828206031051216, 0.30554509550893832])
print(cVals-fVals)

[0. 0. 0.]


In [34]:
cVals=np.array([0.53151219753951129, 0.32546550711829891, 0.057676946334842438])
fVals=np.array([0.53151219753951129, 0.32546550711829891, 0.057676946334842438])
print(cVals-fVals)

[0. 0. 0.]


In [35]:
cVals=np.array([-0.35134552163880967, -0.016206053208934101, -0.029222490499241156])
fVals=np.array([-0.35134552163880967, -0.016206053208934101, -0.029222490499241156])
print(cVals-fVals)

[0. 0. 0.]


In [36]:
cVals=np.array([0, 0.368194924419806, 0.1828206031051216])
fVals=np.array([0, 0.368194924419806, 0.1828206031051216])
print(cVals-fVals)

[0. 0. 0.]


In [37]:
cVals=np.array([-1.8488927466117464e-32, -0.024835037056909561, 0.30554509550893832])
fVals=np.array([-1.8488927466117464e-32, -0.024835037056909561, 0.30554509550893832])
print(cVals-fVals)

[0. 0. 0.]


In [38]:
# Sign changes here.

# This comes from a misunderstanding of how dsign works in fortran
# The line that causes the difference is 
# s = dsign(dsqrt(p*p+q*q+r*r),p)

# In this particular instance, p was 0, and the fortran code assigns s to be positive
# However, I assigned it to be negative in this case.

# Note: If changes this breaks things, consider that some hardware has +-0 and *hopefully* this 
# is not the case. If it is, we will need to implement our own hack for it.
a=1.8488927466117464e-32
b=-1.8488927466117464e-32
print(a+b)

0.0


# Now checking for larger issues. Check with file I/O

In [39]:
cFile = open("outputFileC.txt", 'r')
fFile = open("outputFileFortran.txt", 'r')
cArr=[]
fArr=[]
# Convert cStr to an array
for k in range(6):
    cStr = cFile.readline().split(',')
    tmpArr=[]
    for string in cStr:
        tmpArr.append(float(string))
    cArr.append(tmpArr.copy())
tmpArr=[]
fStr = fFile.readline().split()# Transpose of the matrix
for string in fStr:
    tmpArr.append(float(string))
n = int(np.sqrt(len(tmpArr)))
fArr = np.array(tmpArr).reshape(n,n).T
diffMat=fArr-cArr
print(np.linalg.norm(diffMat,np.inf))
cFile.readline()
while (cStr and fStr):
    cArr=[]
    fArr=[]
    # Convert cStr to an array
    for k in range(6):
        cStr = cFile.readline().split(',')
        tmpArr=[]
        for string in cStr:
            try:
                tmpArr.append(float(string))
            except:
                break
        cArr.append(tmpArr.copy())
    tmpArr=[]
    fStr = fFile.readline().split()# Transpose of the matrix
    for string in fStr:
        tmpArr.append(float(string))
    n = int(np.sqrt(len(tmpArr)))
    fArr = np.array(tmpArr).reshape(n,n).T
    try:
        diffMat=fArr-cArr
    except:
        break
    # Differences happens on 3rd iteration
    print(np.linalg.norm(diffMat,np.inf)) 
    cFile.readline()
cFile.close()
fFile.close()

0.0
0.0
1.1117307432712692e-21
1.1697660258536737e-20
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21
7.858742943863655e-21


In [42]:
cVals=np.array([0.89674688887363407, 1.2957936593131159, -0.21951155843280629, -0.92968854291346248, -0.16940317376546404, -0.71746650111428922])
fVals=np.array([0.89674688887363407, 1.2957936593131159, -0.21951155843280629, -0.92968854291346248, -0.16940317376546404, -0.71746650111428922])
print(cVals-fVals)

[0. 0. 0. 0. 0. 0.]


In [ ]:
cVals=np.array([])
fVals=np.array([])
print(cVals-fVals)

In [43]:
cVals=np.array([0.043044824969539375, 0.66421375702369412, 0.19397643506693549])
fVals=np.array([0.043044824969539375, 0.66421375702369412, 0.19397643506693549])
print(cVals-fVals)

[0. 0. 0.]


In [44]:
cVals=np.array([-0.34820804784426534, -0.20093790532852943, -0.02390770060666858])
fVals=np.array([-0.34820804784426534, -0.20093790532852943, -0.02390770060666858])
print(cVals-fVals)

[0. 0. 0.]


In [45]:
cVals=np.array([0.38749428905676614, -0.20429508815607728, 0.23972846857589053])
fVals=np.array([0.38749428905676614, -0.20429508815607728, 0.23972846857589053])
print(cVals-fVals)

[0. 0. 0.]


In [46]:
cVals=np.array([0.12913434161823584, 0.27760623546056173, -0.56053297596264495])
fVals=np.array([0.12913434161823584, 0.27760623546056173, -0.56053297596264495])
print(cVals-fVals)

[0. 0. 0.]


In [47]:
cVals=np.array([-0.25015722690982523, 0.12268932809169286, -0.20737699675327154])
fVals=np.array([-0.25015722690982523, 0.12268932809169286, -0.20737699675327154])
print(cVals-fVals)

[0. 0. 0.]


In [48]:
cVals=np.array([0.45999826986218995, -0.1122402088072047, -0.23026012970598492])
fVals=np.array([0.45999826986218995, -0.1122402088072047, -0.23026012970598492])
print(cVals-fVals)

[0. 0. 0.]


In [49]:
cVals=np.array([0.27108092344710044, -0.38683808665945807, 0.2238860273543169])
fVals=np.array([0.27108092344710044, -0.38683808665945807, 0.2238860273543169])
print(cVals-fVals)

[0. 0. 0.]


In [50]:
cVals=np.array([-0.43050921333524128, -0.015488359755769759, 0.58113197107678993])
fVals=np.array([-0.43050921333524128, -0.015488359755769759, 0.58113197107678993])
print(cVals-fVals)

[0. 0. 0.]


In [51]:
cVals=np.array([0.16024779447751886, -0.018193961844026753, 0.26392763832692068])
fVals=np.array([0.16024779447751886, -0.018193961844026753, 0.26392763832692068])
print(cVals-fVals)

[0. 0. 0.]


In [52]:
cVals=np.array([-0.27537879447319741, 0.046650041771467067, -0.098630369690601849])
fVals=np.array([-0.27537879447319741, 0.046650041771467067, -0.098630369690601849])
print(cVals-fVals)

[0. 0. 0.]


In [53]:
cVals=np.array([-1.1154070245924115, 1.8038115676869384, -0.299201566209093, 0.51416474639038845, -0.16587185245339389, 0.28504349101703103])
fVals=np.array([-1.1154070245924115, 1.8038115676869384, -0.299201566209093, 0.51416474639038845, -0.16587185245339389, 0.28504349101703103])
print(cVals-fVals)

[0. 0. 0. 0. 0. 0.]


In [54]:
fArr=np.array([0.27108092344710044, 0.53558474478549967, 0.16024779447751886, -0.27537879447319741, 0, 0, -0.38683808665945807, -0.016979746039624096, -0.017946582838400251, 0.046224931818662308, 0, 0, 0.2238860273543169, -0.33744077893259461, 0.41629300198418562, -0.36046355310639133, 0, 0, 0.12913434161823584, -0.30622962550803368, -0.46369104017506191, -0.33100753554395901, 0.019561581231585651, 0, -0.25015722690982523, -0.21281258358406496, -0.15172667316195865, 0.0057861417330816456, -0.10589154634751163, 0.0014925316771684013, 0.45999826986218995, -0.095489216286958792, -0.23303864786575104, 0.23196848453079733, 0.75297598167679758, 0.22400644004666498])
cArr=np.array([0.27108092344710044, 0.53558474478549967, 0.16024779447751886, 
  -0.27537879447319741, 0, 0, -0.38683808665945807, -0.016979746039624096, 
  -0.017946582838400251, 0.046224931818662308, 0, 0, 0.2238860273543169, 
  -0.33744077893259461, 0.41629300198418562, -0.36046355310639133, 0, 0, 
  0.12913434161823584, -0.30622962550803368, -0.46369104017506191, 
  -0.33100753554395901, 0.019561581231585651, 0, -0.25015722690982523, 
  -0.21281258358406496, -0.15172667316195865, 0.0057861417330816456, 
  -0.10589154634751163, 0.0014925316771684013, 0.45999826986218995, 
  -0.095489216286958792, -0.23303864786575104, 0.23196848453079733, 
  0.75297598167679758, 0.22400644004666498])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [55]:
fArr=np.array([0.27108092344710044, 0.53558474478549967, 0.16024779447751886, -0.27537879447319741, 0, 0, 0.31153565290706808, 0.07013818446014948, -0.37836789233947993, 0.02518501100415952, -0.01005787545293322, 0, 0.10804548146761314, -0.35189119144649805, -0.32600968785116585, -0.37952484095983746, 0.01067436361179367, 0, 0.32820123037889731, -0.28139722646819915, 0.3729743998707179, -0.31287907627131728, 0.0070597991787706219, 0,-0.25015722690982523, -0.21281258358406496, 0.1481364746061184, 0.015778771696270358, -0.10988219886699641, 0.0014925316771684013, 0.45999826986218995, -0.095489216286958792, 0.2370147672066861, 0.2476325295283669, 0.74672039522306621, 0.22400644004666498])
cArr=np.array([0.27108092344710044, 0.53558474478549967, 0.16024779447751886, 
  -0.27537879447319741, 0, 0, 0.31153565290706808, 0.07013818446014948, 
  -0.37836789233947993, 0.02518501100415952, -0.01005787545293322, 0, 
  0.10804548146761314, -0.35189119144649805, -0.32600968785116585, 
  -0.37952484095983746, 0.01067436361179367, 0, 0.32820123037889731, 
  -0.28139722646819915, 0.3729743998707179, -0.31287907627131728, 
  0.0070597991787706219, 0, -0.25015722690982523, -0.21281258358406496, 
  0.1481364746061184, 0.015778771696270358, -0.10988219886699641, 
  0.0014925316771684013, 0.45999826986218995, -0.095489216286958792, 
  0.2370147672066861, 0.2476325295283669, 0.74672039522306621, 0.22400644004666498])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [57]:
cArr=np.array([0.27108092344710044, 0.53558474478549967, 0.16024779447751886, 
  -0.27537879447319741, 0, 0, 0.31153565290706808, 0.07013818446014948, 
  -0.37836789233947993, 0.02518501100415952, -0.01005787545293322, 0, 
  -0.13626315303065181, 0.36405955592180783, 0.30428302459867013, 
  -0.40004048876691028, -0.014037744093651855, 3.9674872055603727e-05, 
  -0.32857252889451483, 0.2495876521853112, -0.38885523465125094, 
  -0.28707707621167206, -7.7106031875989224e-05, 3.466371126309389e-07, 
  -0.23552188388373166, -0.23124111343641834, 0.15348774498390977, 
  0.0008261249234626563, -0.10936206189794601, 0.0014917933995120388, 
  0.45996609519950338, -0.095464060859460173, 0.23697593565521669, 
  -0.22132768645810807, 0.75495071294995764, 0.22398317776856627])
fArr=np.array([0.27108092344710044, 0.53558474478549967, 0.16024779447751886, -0.27537879447319741, 0, 0, 0.31153565290706808, 0.07013818446014948, -0.37836789233947993, 0.02518501100415952, -0.01005787545293322, 0, -0.13626315303065181, 0.36405955592180783, 0.30428302459867013, -0.40004048876691028, -0.014037744093651855, 3.9674872055603727e-05, -0.32857252889451483, 0.2495876521853112, -0.38885523465125094, -0.28707707621167206, -7.7106031875989224e-05, 3.466371126309389e-07, -0.23552188388373166, -0.23124111343641834, 0.15348774498390977, 0.0008261249234626563, -0.10936206189794601, 0.0014917933995120388, 0.45996609519950338, -0.095464060859460173, 0.23697593565521669, -0.22132768645810807, 0.75495071294995764, 0.22398317776856627])
print(fArr[22])
print(fArr-cArr)

-7.710603187598922e-05
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [58]:
cArr=np.array([0.27108092344710044, 0.53558474478549967, 0, 0, 0, 0, 0.31153565290706808, 
  0.07013818446014948, -0.37836789233947993, 0, 0, 0, -0.13626315303065181, 
  0.36405955592180783, 0.30428302459867013, -0.40004048876691028, 0, 0, 
  -0.32857252889451483, 0.2495876521853112, -0.38885523465125094, 
  -0.28707707621167206, 7.7106811041236303e-05, 0, 0.23758730205536457, 
  0.23080961379317877, -0.15242085808631411, -0.0018211050744413415, 
  -0.11275591172347077, 2.204751346898009e-05, 0.45890264808919279, 
  -0.096502650946680479, 0.23766355202290237, -0.22132173605770311, 
  -0.75343687203697662, 0.22737702759409104])
fArr=np.array([0.27108092344710044, 0.53558474478549967, 0, 0, 0, 0,0.31153565290706808, 0.07013818446014948, -0.37836789233947993, 0, 0, 0,-0.13626315303065181, 0.36405955592180783, 0.30428302459867013, -0.40004048876691028, 0, 0,-0.32857252889451483, 0.2495876521853112, -0.38885523465125094, -0.28707707621167206, 7.7106811041236303e-05, 0,0.23758730205536457, 0.23080961379317877, -0.15242085808631411, -0.0018211050744413415, -0.11275591172347077, 2.204751346898009e-05,0.45890264808919279, -0.096502650946680479, 0.23766355202290237, -0.22132173605770311, -0.75343687203697662, 0.22737702759409104])
print(fArr-cArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [59]:
fArr=np.array([0.52473332909357229, 0.11806280656168155, -0.02226358033428194, -0.27094712789397113, 0, 0,-0.24761886948589026, -0.19137247018060793, -0.12253157547731165, -0.068102087808861705, 0, 0,-0.23917999290576278, 0.54018128854249126, 0.31214127359295574, -0.28632525591528002, 0, 0,-0.16293590277366668, 0.29122012913431894, -0.45837214614057098, -0.28707707621167206, 7.7106811041236303e-05, 0,-0.34268444121536379, 0.084959323663184316, 0.09111645827554915, -0.0018211050744413415, -0.11275591172347077, 2.204751346898009e-05,-0.081555959289370983, -0.23234597884183122, 0.46449148285364172, -0.22132173605770311, -0.75343687203697662, 0.22737702759409104])
cArr=np.array([0.52473332909357229, 0.11806280656168155, -0.02226358033428194, 
  -0.27094712789397113, 0, 0, -0.24761886948589026, -0.19137247018060793, 
  -0.12253157547731165, -0.068102087808861705, 0, 0, -0.23917999290576278, 
  0.54018128854249126, 0.31214127359295574, -0.28632525591528002, 0, 0, 
  -0.16293590277366668, 0.29122012913431894, -0.45837214614057098, 
  -0.28707707621167206, 7.7106811041236303e-05, 0, -0.34268444121536379, 
  0.084959323663184316, 0.09111645827554915, -0.0018211050744413415, 
  -0.11275591172347077, 2.204751346898009e-05, -0.081555959289370983, 
  -0.23234597884183122, 0.46449148285364172, -0.22132173605770311, 
  -0.75343687203697662, 0.22737702759409104])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
fArr=np.array([0.52473332909357229, -0.29638967494923635, -0.02226358033428194, -0.27094712789397113, 0, 0,-0.068279838655236402, -0.41339063331770898, -0.30398713880883221, 0.263842552160934, 7.0487843398270661e-05, 0,-0.24881373645439525, -0.43101096738309336, 0.37469993224153836, 0.33855433127290324, -3.7864697018259822e-06, 0,-0.28017828275824391, -0.13949694581983313, -0.30881196728259364, -0.12761757172315358, 3.1025584429740336e-05, 0,-0.34268444121536379, -0.028662876996754127, 0.097220021663391484, 0.072459084590659764, -0.11275591172347077, 2.204751346898009e-05,-0.081555959289370983, -0.074880567046250707, 0.45603274752986894, -0.32426429997508205, -0.75343687203697662, 0.22737702759409104])
cArr=np.array([0.52473332909357229, -0.29638967494923635, -0.02226358033428194, 
  -0.27094712789397113, 0, 0, -0.068279838655236402, -0.41339063331770898, 
  -0.30398713880883221, 0.263842552160934, 7.0487843398270661e-05, 0, 
  -0.24881373645439525, -0.43101096738309336, 0.37469993224153836, 
  0.33855433127290324, -3.7864697018259822e-06, 0, -0.28017828275824391, 
  -0.13949694581983313, -0.30881196728259364, -0.12761757172315358, 
  3.1025584429740336e-05, 0, -0.34268444121536379, -0.028662876996754127, 
  0.097220021663391484, 0.072459084590659764, -0.11275591172347077, 
  2.204751346898009e-05, -0.081555959289370983, -0.074880567046250707, 
  0.45603274752986894, -0.32426429997508205, -0.75343687203697662, 
  0.22737702759409104])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
fArr=np.array([0.52473332909357229, -0.29638967494923635, -0.02226358033428194, -0.27094712789397113, 0, 0,-0.068279838655236402, -0.41339063331770898, 0.40251841928104543, 0.263842552160934, 7.0487843398270661e-05, 0,0.0041962491403326752, 0.23406268053558504, 0.14414974196544397, -0.5744152034030604, -5.9357362452540374e-05, 3.8608958057088181e-09,-0.37466416408944497, -0.38786686539451209, 0.07293204230923625, 0.10292032042202048, 2.2281902326602589e-05, -1.4418408904803985e-09,-0.34270968394422641, -0.028729231191149361, -0.025966601765875501, 0.11856246606314177, -0.11274361359255047, 2.2047513083779698e-05,-0.081555959289370983, -0.074880567046250707, -0.55708237934950477, 0.054080750036113623, -0.75333579385069749, 0.22737702759409104])
cArr=np.array([0.52473332909357229, -0.29638967494923635, -0.02226358033428194, 
  -0.27094712789397113, 0, 0, -0.068279838655236402, -0.41339063331770898, 
  0.40251841928104543, 0.263842552160934, 7.0487843398270661e-05, 0, 
  0.0041962491403326752, 0.23406268053558504, 0.14414974196544397, 
  -0.5744152034030604, -5.9357362452540374e-05, 3.8608958057088181e-09, 
  -0.37466416408944497, -0.38786686539451209, 0.07293204230923625, 
  0.10292032042202048, 2.2281902326602589e-05, -1.4418408904803985e-09, 
  -0.34270968394422641, -0.028729231191149361, -0.025966601765875501, 
  0.11856246606314177, -0.11274361359255047, 2.2047513083779698e-05, 
  -0.081555959289370983, -0.074880567046250707, -0.55708237934950477, 
  0.054080750036113623, -0.75333579385069749, 0.22737702759409104])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [62]:
fArr=np.array([0.52473332909357229, -0.29638967494923635, -0.02226358033428194, -0.27094712789397113, 0, 0,-0.068279838655236402, -0.41339063331770898, 0.40251841928104543, 0.263842552160934, 7.0487843398270661e-05, 0,0.0041962491403326752, 0.23406268053558504, 0.14414974196544397, 0.57441520646991551, -5.9357362452540374e-05, 3.8608958057088181e-09,0.37469957554578698, 0.38786983156381261, -0.0729293623978928, 0.10293257174550532, -4.3568781835621757e-12, 3.1461324473261955e-16,-0.34267096608411401, -0.028689150702425021, -0.02597413808123818, -0.11854017910150574, -0.11275586527927405, 2.2048309993564384e-05,-0.081555961807771693, -0.074880569653283505, -0.55708237885930567, -0.054002902737488936, -0.75334137827848735, 0.22737702795732978])
cArr=np.array([0.52473332909357229, -0.29638967494923635, -0.02226358033428194, 
  -0.27094712789397113, 0, 0, -0.068279838655236402, -0.41339063331770898, 
  0.40251841928104543, 0.263842552160934, 7.0487843398270661e-05, 0, 
  0.0041962491403326752, 0.23406268053558504, 0.14414974196544397, 
  0.57441520646991551, -5.9357362452540374e-05, 3.8608958057088181e-09, 
  0.37469957554578698, 0.38786983156381261, -0.0729293623978928, 
  0.10293257174550532, -4.3568781835621757e-12, 3.1461324473261955e-16, 
  -0.34267096608411401, -0.028689150702425021, -0.02597413808123818, 
  -0.11854017910150574, -0.11275586527927405, 2.2048309993564384e-05, 
  -0.081555961807771693, -0.074880569653283505, -0.55708237885930567, 
  -0.054002902737488936, -0.75334137827848735, 0.22737702795732978])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
fArr=np.array([0.52473332909357229, -0.29638967494923635, 0, 0, 0, 0,-0.068279838655236402, -0.41339063331770898, 0.40251841928104543, 0, 0, 0,0.0041962491403326752, 0.23406268053558504, 0.14414974196544397, 0.57441520646991551, 0, 0,0.37469957554578698, 0.38786983156381261, -0.0729293623978928, 0.10293257174550532, 4.3568781949213971e-12, 0,0.34266507597723034, 0.028683743448924128, 0.025933910702367089, 0.11853627920478629, -0.11270146578615313, 2.5089977558438325e-06,-0.08158070610707957, -0.074882641121844784, -0.55708425301769915, -0.054011462466560731, 0.75336593558623666, 0.22732262846420884])
cArr=np.array([0.52473332909357229, -0.29638967494923635, 0, 0, 0, 0, 
  -0.068279838655236402, -0.41339063331770898, 0.40251841928104543, 0, 0, 0, 
  0.0041962491403326752, 0.23406268053558504, 0.14414974196544397, 
  0.57441520646991551, 0, 0, 0.37469957554578698, 0.38786983156381261, 
  -0.0729293623978928, 0.10293257174550532, 4.3568781949213971e-12, 0, 
  0.34266507597723034, 0.028683743448924128, 0.025933910702367089, 
  0.11853627920478629, -0.11270146578615313, 2.5089977558438325e-06, 
  -0.08158070610707957, -0.074882641121844784, -0.55708425301769915, 
  -0.054011462466560731, 0.75336593558623666, 0.22732262846420884])
print(cArr-fArr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
